config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"



  resources :events
  resources :venues
  resources :performers
  resources :purchases
  resources :memberships

  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'profile', to: 'users#profile'   
  resources :users

end

app/models/active_api.rb
require("net/http")

class ActiveApi

  API_URL = "https://api.seatgeek.com/2"
  CLIENT_ID = 'NDIwNjA1MnwxNDU1MzU1Mjcx'
  REQUEST_DEFAULTS = { :parse? => false }

  def self.uri(path = '')
    url_string = "#{API_URL}/#{self.endpoint}/#{path}"
    # byebug
    return URI.parse(url_string)
  end

  def self.request(path = '', given_options = {})
    options = REQUEST_DEFAULTS.merge(given_options)

    uri = self.uri(path)
    response = Net::HTTP.get_response(uri)
    body = response.body

    if options[:parse?]
      body = JSON.parse(body)
    end

    return body
  end

  def self.all
    self.request
  end

  def self.find(id)
    self.request(id)
  end

  def self.find_by(query_hash)
    self.request("?#{query_hash.keys.first}=#{query_hash.values.first}")
  end

  def self.get_band_id(band_name)
    response = request("?slug="+ band_name.parameterize)
    parsed_response = ActiveSupport::JSON.decode(response)
    parsed_response["performers"][0]["id"] 
  end

  def self.get_recommendations(bands_ids)
    #Your code goes here.../recommendations/performers?performers.id=35&client_id=NDIwNjE0MHwxNDU1MzY2NTMw
    path = 'performers?'
    bands_ids.each_with_index do |index, id|
      path += 'performers.id=' + id.to_s + '&'
    end 
    path += 'client_id=' + CLIENT_ID
    self.request(path)
  end
end

app/models/api.rb
class ActiveApi
  API_URL = "https://api.seatgeek.com/2"
  REQUEST_DEFAULTS = { :parse? => false }

  def self.uri(path)
    url_string = "#{API_URL}/#{self.endpoint}/#{path}"
    return URI.parse(url_string)
  end

  def self.request(path, given_options = {})
    options = REQUEST_DEFAULTS.merge(given_options)

    uri = self.uri(path)
    response = Net::HTTP.get_response(uri)
    body = response.body

    if options[:parse?]
      body = JSON.parse(body)
    end

    return body
  end
end

app/models/event.rb
class Event < ActiveApi
  def self.endpoint
    "events"
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base

	def self.get_favs_list(user_id)
		favs = where user_id: user_id
	end
end

app/models/performer.rb
class Performer < ActiveApi
  def self.endpoint
    "performers"
  end
end

app/models/recommendation.rb
class Recommendation < ActiveApi
  def self.endpoint
    "recommendations"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ActiveApi
  def self.endpoint
    "venues"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index

    @events = Event.all
    respond_to do |format|
      format.html
      format.json {}
    end
#     render(:json => @perfomers)86
  end

  def show
    @event = ActiveSupport::JSON.decode(Event.find(params[:id]))
    unless @event
      render json: {error: "city not found"}, status: 404
      console.log("there are no cities")
      return
    end
    respond_to do |format|
      format.html
      format.json {}
    end
  end
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  def index
    @performers = Performer.all
    render(:json => @performers)
  end

  def show
    @performer = Performer.find(params[:id])
    render(:json => @performer)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def create
    UserMail.purchase_mail(current_user).deliver_later
    flash[:notice] = "Purchase successful! Thank you for your money MUAJAJAJAJAJAJAJAJAJAJAJA"
    redirect_to action: "show", controller: "events", id: params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  # este método muestra los datos del usuario
  # con el que estoy logueado
  def profile
    @user = current_user
    @favs = Membership.get_favs_list(current_user)    
    render 'users/profile'
  end

  # GET /users/1
  # GET /users/1.json
  def show
  	@user = current_user
    @favs = Membership.get_favs_list(current_user)  	
  end

  
  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.all
    render(:json => @venues)
  end

  def show
    @venue = Venue.find(params[:id])
    render(:json => @venue)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Tktplatform</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="alert alert-success">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul class="list-unstyled">
        <li class="text-center">
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

    <div id="top_bar">
        <div class="container-fluid">
            <div class="row" style="background-color:rgba(0,100,100,0.1);">
                <div class="col-sm-12">
                    <div class="col-sm-4">
                        <nav class="navbar-default" style="background-color:transparent">
                                <%= button_to 'HOME', root_path, :action => 'get', :method => 'get', class: 'btn btn-default btn-sm tpnt_button pull-left'%>
                                <%= button_to 'SEARCH', events_path, :action => 'get', :method => 'get', class: 'btn btn-default btn-sm tpnt_button pull-left'%>    
                        </nav>
                    </div>
                    
                    <div class="col-sm-4">
                        <%= link_to image_tag("http://www.clipartbest.com/cliparts/9T4/zbk/9T4zbka7c.png", size: "100"), '/', size: "10px", class: 'top_image img-responsive center-block' %>
                    </div>

        <% if user_signed_in? %>
            
                    <div class="col-sm-4">
                        <%= button_to 'Sign out', destroy_user_session_path, :action => 'destroy', :method => 'delete', class: 'btn btn-danger btn-sm text-capitalize btn-primary pull-right'%>

                        <%= button_to 'Profile', edit_user_registration_path, :action => 'get', :method => 'get', class: 'btn btn-success btn-sm text-capitalize btn-primary pull-right'%>
                        
                    </div>
                </div>
            </div>

        <% else %>

                    <div class="col-sm-4">
                        <%= button_to 'Sign Up', new_user_registration_path, :action => 'get', :method => 'get', class: 'btn btn-success btn-sm text-capitalize btn-primary pull-right'%>
                        <%= button_to 'Sign in', new_user_session_path, :action => 'destroy', :method => 'delete', class: 'btn btn-default btn-sm text-capitalize btn-primary pull-right'%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <div class="container">
       <%= yield %>
     </div>

</body>
</html>

app/views/layouts/new.html.erb
	<a href="#myModal">  Ir a modal</a>

app/views/user_mail/purchase_mail.html.erb
test

app/views/user_mail/purchase_mail.text.erb
test